name: Check for infrastructure drift

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  check_drift:
    strategy:
      fail-fast: false
      matrix:
        path: ["leo69.lol", "leoconforti.us", "ltgk.net", "ltgk.page"]
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for drift
        uses: dflook/terraform-check@v2
        with:
          path: ${{ matrix.path }}
          variables: |
            do_token           = "${{ secrets.DO_ACCESS_TOKEN }}"
            porkbun_api_key    = "${{ secrets.PORKBUN_API_KEY }}"
            porkbun_secret_key = "${{ secrets.PORKBUN_SECRET_KEY }}"
