name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        path: ["leo69.lol", "leoconforti.us", "ltgk.page"]
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: ${{ matrix.path }}
          variables: |
            do_token           = "${{ secrets.DO_ACCESS_TOKEN }}"
            porkbun_api_key    = "${{ secrets.PORKBUN_API_KEY }}"
            porkbun_secret_key = "${{ secrets.PORKBUN_SECRET_KEY }}"

  fmt-check:
    strategy:
      fail-fast: false
      matrix:
        path: ["leo69.lol", "leoconforti.us", "ltgk.page"]
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v2
        with:
          path: ${{ matrix.path }}
          variables: |
            do_token           = "${{ secrets.DO_ACCESS_TOKEN }}"
            porkbun_api_key    = "${{ secrets.PORKBUN_API_KEY }}"
            porkbun_secret_key = "${{ secrets.PORKBUN_SECRET_KEY }}"
